# This file was adapted from work by Keith James (keithj). The original source
# can be found as part of the wtsi-npg/data_handling project here:
#
#   https://github.com/wtsi-npg/data_handling

sudo: required

language: perl

perl:
  - "5.16"

env:
  global:
    - DNAP_UTILITIES_VERSION="0.5.1"
    - HTSLIB_VERSION="1.3.1"
    - SAMTOOLS_VERSION="1.3.1"
    - ILLUMINA2BAM_VERSION="1.19"
    - PICARD_VERSION="2.5.0"
    - TOOLS_INSTALLED=1
    - TEST_AUTHOR=1

before_install:
 - ./.travis/before_install.sh
install:
 - ./.travis/install.sh
script:
 - ./.travis/script.sh

