# This file was adapted from work by Keith James (keithj) and Jaime Tovar Corona
# (jmtc). The original source can be found as part of the wtsi-npg/data_handling
# and wtsi-npg/qc projects here:
#
#   https://github.com/wtsi-npg/data_handling
#   https://github.com/wtsi-npg/npg_qc

sudo: required

language: perl

perl:
  - "5.16"

env:
  global:
    - SH=bash
    - DNAP_UTILITIES_VERSION="0.5.1"
    - BWA_VERSION="0.5.10-mt_fixes.2"
    - BWA0_6_VERSION="v0.7.13"
    - BOWTIE_VERSION="v1.0.1-dkj-fopen_with_MM"
    - BOWTIE2_VERSION="v2.2.7"
    - PB_CALIBRATION_VERSION="v10.26"
    - STADEN_IO_LIB_VERSION="1.14.6"
    - LIBMAUS_VERSION="0.0.196-release-20150326095654"
    - BIOBAMBAM_VERSION="0.0.191-release-20150401083643"
    - HTSLIB_VERSION="1.3"
    - SAMTOOLS1_VERSION="1.3.1-npg-May2016"
    - SAMTOOLS_VERSION="0.1.18"
    - ILLUMINA2BAM_VERSION="1.18"
    - PICARD_VERSION="1.72"
    - SMALT_VERSION="0.7.6"
    - TOOLS_INSTALLED=1
#    - TEST_AUTHOR=1 # disabled to avoid perl critic complaints
    - CLASSPATH="/tmp/picard-tools-${PICARD_VERSION}:/tmp/illumina2bam/dist"
#    - PATH="$PATH:/tmp/bowtie:/tmp/bowtie2:/tmp/bin:/tmp/samtools-0.1.19"
    - PATH="$PATH:/tmp/bin"


before_install:
 - ./.travis/before_install.sh
install:
 - ./.travis/install.sh
script:
 - ./.travis/script.sh
after_script:
 - ls -al /tmp
 - ls -al /tmp/Ref_Maker_test*/*
 - echo "HOME is at $HOME"
 - ls -al $HOME/
 - find /tmp -name E-coli-K12.fa.dict -exec cat {} \;
